### ISSUE TITLE
Add original FW to the installer

### ISSUE THREAD

**Issue by Secarius** [Cp0204/CubeFX#1]
[Zimacube_esp32c3_dump.zip](https://github.com/user-attachments/files/16431636/Zimacube_esp32c3_dump.zip)

the firmware is attached

**Comment by Cp0204** [comment]
Thank you!  The option to flash back to the official firmware is now available. 

![image](https://github.com/user-attachments/assets/a4b0a0a8-f07d-450b-bf57-5dad90984a52)
